/*
 * Created on 26.09.2004
 *
 * @author Felix Burkhardt
 */
package emofilt;

import java.awt.Color;

import org.apache.log4j.Logger;

import emofilt.gui.MainFrame;

/**
 * 
 * Declaration of global constants like internal designators etc..
 * 
 * @author Felix Burkhardt
 */
public class Constants {
	/** The version string. */
	public static final String VERSION = "1.1";
	public static final String TAGGER_VERSION = "0.1";

	public static final String PHO_PRELIMINARY = "; pho file generated by emoFilt (http://emofilt.sourceforge.net)\n"
			+ "; a '; -' denotes a syllable start followed by the stresstype (if any)\n"
			+ "; emofilt version: ";

	/** The webpage URL string. * */
	public static final String EMOFILT_WEBPAGE = "emofilt.sourceforge.org";

	/** The Duration of one f0val for interpolated f0-contour in msec. */
	public static final int frameSize = 10;

	/** The default name of the log4j configuration file. */
	protected static final String loggerDefaultConfigFile = "logConfig.xml";

	/** The default name for languages/voices file. */
	protected static final String languagesDefaultFile = "languages.xml";

	/** The default name for emotions file. */
	protected static final String emotionsDefaultFile = "emotions.xml";

	/** The default name for emotion. */
	protected static final String emotionsDefaultName = "neutral";
	/** String to name a non-emotional state */
	public static final String NEUTRAL_EMOTION = "neutral";
	/** Color for a non-emotional state */
	public static final Color NEUTRAL_COLOR = Color.black;
	/**
	 * The default global rate of modification damping or amplification. Should
	 * range from -1 to 1.
	 */
	protected static final String globalRate = "0";

	public static final String PHO_GEN_SUFFIX="_phonGenerator";
	
	/** The default name of the configuration file. */
	protected static final String configDefaultFile = "emofiltConfig.ini";

	/** The minimum F0 value. */
	public static final int minF0Val = 50;

	/** The String to start a comment in PHO-files. */
	public static final String phoFileCommentStart1 = ";";

	/** The String to start a comment in PHO-files. */
	public static final String phoFileCommentStart2 = "#";

	/** The String to start a syllable sign in PHO-files. */
	public static final String phoFileSyllableStart = "; -";

	/** The String to denote focus stress in syllable description. */
	public static final String focusStressSymbol = "focus";

	/** The String to denote word stress in syllable description. */
	public static final String wordStressSymbol = "word";

	/**
	 * The rate of change in duration of phoneme is converted to centralized
	 * variant.
	 */
	public static final int centralizedDurationChanged = 80;

	/**
	 * The rate of change in duration of phoneme is converted to decentralized
	 * variant.
	 */
	public static final int decentralizedDurationChanged = 120;

	/** Identifier for straight f0 contour */
	public final static String CONTOUR_STRAIGHT = "straight";

	/** Identifier for falling f0 contour */
	public final static String CONTOUR_FALL = "fall";

	/** Identifier for rising f0 contour */
	public final static String CONTOUR_RISE = "rise";

	/** Identifier for syllable focus stress */
	public final static String FOCUS_STRESS = "focus";

	/** Identifier for syllable word stress */
	public final static String WORD_STRESS = "word";

	/** Identifier for syllable without stress */
	public final static String UNSTRESS = "none";

}