<html>
<meta name="keywords" content="text-to-speech, tts, emotion, simulation, synthesis">
<meta name="title" content="emofilt: a tool to modify MBROLA's output">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title> emofilt </title>
<link rel="stylesheet" type="text/css" href="format.css" />
<link rel="meta" title="DOAP" type="application/rdf+xml"
        href="doap.rdf" />

</head>

<body>

<table>

<tr><td colspan="2">


<table width="100%">
<tr>
<td align="left" valign="middle" width=10%><h1>emofilt</h1></td>
<td align="left" valign="middle"><image src="images/logo.jpg" border="0" alt="emofilt-logo"/></td>
<td align="right">
<a href="http://sourceforge.net/projects/emofilt"><img src="http://sflogo.sourceforge.net/sflogo.php?group_id=121061&type=15" width="150" height="40" border="0" alt="Get emofilt - emotional speech synthesis at SourceForge.net. Fast, secure and Free Open Source software downloads" /></a>
</td>
</tr>
</table>

</td>
</tr>
<tr>

<td valign="top" bgcolor="#eeeeee">

<table>
<tr class="tablecell1"><td>
<a href="index.html">description</a>
</td></tr>
<tr class="tablecell2"><td>
<a href="changelog.html">change log</a>
</td></tr>
<tr class="tablecell1"><td>
<a href="readme.html">readme</a>
</td></tr>
<tr class="tablecell2"><td>
<a href="doc/index.html">javadoc</a>
</td></tr>
<tr class="tablecell1"><td>
<a href="faq.html">FAQ</a>
</td></tr>
<tr class="tablecell2"><td>
<a href="http://sourceforge.net/projects/emofilt">project main page</a>
</td></tr>
<tr class="tablecell1"><td>
<a href="http://sourceforge.net/project/showfiles.php?group_id=121061">download</a>
</td></tr>
<tr class="tablecell2"><td>
<a href="http://emoSamples.syntheticspeech.de/index.html#emofilt">further samples</a>
</td></tr>
<tr class="tablecell1"><td>
<a href="languages.html">languages config</a>
</td></tr>
<tr class="tablecell2"><td>
<a href="emotions.html">emotions config</a>
</td></tr>
<tr class="tablecell1"><td>
<a href="config.html">configuration</a>
</td></tr>
<tr class="tablecell2"><td>
<a href="links.html">usecases</a>
</td></tr>
</table>
</td>

<td>

last update: <font color="#FF0000">2011/2/24</font>,
<p>